plugins {
    id 'java-library'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 8
}

dependencies {
    api project(':modules:api')
    api "com.google.code.gson:gson:${project.property('gsonVersion')}"
    api "com.squareup.okhttp3:okhttp:${project.property('okhttpVersion')}"
    compileOnly 'org.jetbrains:annotations:26.1.0'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation "com.squareup.okhttp3:mockwebserver:${project.property('okhttpVersion')}"
}

test {
    useJUnitPlatform()
}
